### ISSUE TITLE
Passed JVM options lost

### ISSUE THREAD

**Issue by chrisjowen** [lewismj/cucumber#21]
Hi, 

I am having trouble passing JVM arguments via:

`sbt -DsomeArg=someVal cucumber`

The argument is lost, as  a quick test I added the following to my steps:

```
  Before() { scenario =>
    println("OPTS:::::")
    println(System.getProperty("someArg"))
  }
```

Which results in `null`. Similar tests work with sbt run etc 

Cheers, Chris

**Comment by lewismj** [comment]
Hi,

Apologies for the delay, I'll take a look at this and another request 
over the weekend.
Hopefully ship a new version.

Regards,
Mike

**Comment by chrisjowen** [comment]
Delay? I literally asked this 4 mins ago, I wouldn't call that a delay :)

**Comment by lewismj** [comment]
I think this should be an easy fix:
~~~
  val runtimeMXBean = ManagementFactory.getRuntimeMXBean

  import scala.collection.JavaConversions._
  val args = runtimeMXBean.getInputArguments.toList
~~~
Gets me the arguments passed in. I'll do that fix in the next couple of hours.

**Comment by lewismj** [comment]
The cucumber-plugin should now pass through the JVM arguments.  Will look at the runner too, basically two ways Cucumber can be invoked, one through its own command 'sbt cucumber' the other is hooking into the "JUnit" test frameworks. I need to check the later. But, if you are using 'sbt cucumber' that should now pass through arguments fine and return error on failing test. Checked into master, may take a bit of time to hit Maven.

**Comment by chrisjowen** [comment]
Your a star :)

**Comment by lewismj** [comment]
No worries, like the other one, I'll leave the open issue for a day or two in case of problems, then I'll close it down.

**Comment by eugeniyk** [comment]
for 0.1.4 I still have this issue
could you please help?

**Comment by lewismj** [comment]
Will take a look this evening, can generate a new release if required.

**Comment by lewismj** [comment]
Just wondering, I guess "sbt -DsomeArg=someVal test" on the runner doesn't work? The plugin creates its own JVM for the new command. The runner hooks into the test framework..., will investigate.

**Comment by eugeniyk** [comment]
I tried many ways
sbt "-DsomeArg=someVal cucumber --tags @debug"
sbt -DsomeArg=someVal "cucumber --tags @debug"
sbt -DsomeArg=someVal cucumber

none of them works
however in CI, where we lunch it with with java & teamcity cucumber plugin, flags are passed

**Comment by danewatts** [comment]
@lewismj hey, I have plugin v0.1.6 and facing the exact same issue. Im passing in -Dbrowser and getProperty is returning null. Im using scala 2.11

**Comment by lewismj** [comment]
I had a quick look at this, couldn't immediately spot where to add it cleanly, will take another look in a day or two.

**Comment by lewismj** [comment]
Finally, getting a chance to look at this today. Busy at work Mifid2 :(

**Comment by lewismj** [comment]
Looking first at the Runner, if I do:

tangaroa:example lewismj$ `export K="2049"` and the run `sbt test` with `    println(System.getenv("K"))` in one of the steps, I can see that the env is picked up:
 
Feature: Multiplication
  In order to avoid making mistakes
  As a dummy
  I want to multiply numbers

  @my-test
  Scenario: Multiply two variables  # Multiplication.feature:7
**2049**
    Given a variable x with value 2 # MultiplicationSteps.scala:44
    And a variable y with value 3   # MultiplicationSteps.scala:49
    When I multiply x * y           # MultiplicationSteps.scala:53
    Then I get 6                    # MultiplicationSteps.scala:57

1 Scenarios (1 passed)
4 Steps (4 passed)
0m0.117s

Which I think is fine for the runner (running tests as a JUnit framework), I will look at the standalone plugin...

**Comment by lewismj** [comment]
unfortunately, the sbt 1.0.x interface has changed a bit, so cross-compiling different versions may be tricky. looking into the changes.

**Comment by lewismj** [comment]
I've got the plugin building for SBT 1.0, unfortunately, the Fork interface changed, so can't cross compile. Finally ... will take a look at the env passing next...

**Comment by lewismj** [comment]
For the next (sbt 1.0) version of the plugin (not the runner) you can override the environment variables by setting an 'envProperties' flag, e.g.

`CucumberPlugin.envProperties := Map("K"->"2049")`

The runner documentation and plugin doc should show how to filter by tags.
e.g.
`sbt "cucumber --tags ~@my-tag"`

Will be a few hours before its checked in and published. 

n.b. Unfortunately the SBT interface has changed so the next version of the plugin will be SBT 1.0.2 only.
