### ISSUE TITLE
Piping standard out to forked process

### ISSUE THREAD

**Issue by chrisjowen** [lewismj/cucumber#23]
Hey, 

Thanks for the great work so far, I was also wondering if it is possible to get the forked process to write to standard out from the parent process. I am loosing my log messages when cucumber runs and I am assuming this is the cause. 

Chris

**Comment by chrisjowen** [comment]
Doh, ok nevermind seems like the out put is been piped as expected it was my dumb fault as I had error level reporting in my test slf4j config. Closing with shame now :)

**Comment by lewismj** [comment]
ok, no worries.
