### ISSUE TITLE
CucumberPlugin.features option is not used by the Cucumber Runner plugin

### ISSUE THREAD

**Issue by adamh128** [lewismj/cucumber#27]
If I define an alternative location for feature files in the build.sbt file as follows:
`CucumberPlugin.features := List("src/test/features")`

Then **sbt cucumber** works as required, but **sbt test** fails to find the feature files as it appears to only look in the **src/test/resources** directory.

**Comment by lewismj** [comment]
Hi,
I will take a look, I will hopefully have a couple of hours tomorrow to investigate. Hopefully should be a quick fix to make.
Rds,
Mike

**Comment by lewismj** [comment]
Hi,
In the runner, if you have features files outside of the resources. Add the directory to the classpath:

e.g. In the build.sbt file:

unmanagedClasspath in Test += baseDirectory.value / "src/test/features"

This works for me, the Runner is something that basically hooks into JUnit runner vs the plugin that provides a new command.  I may look at trying to combine them, when I originally wrote it, wanted to keep them separate (we had projects where BDD feature files had to be run separately to the test/it tests that we were running on check-in), the runner was added in case someone wanted to hook in the cucumber into 'sbt test'.

I did a quick test, that seems to work for me, pls. let me know if you still have problems.

**Comment by adamh128** [comment]
Hi Michael,
thanks for the info :)
 

    On Wednesday, 15 February 2017, 2:18, Michael Lewis <notifications@github.com> wrote:
 

 Hi,
In the runner, if you have features files outside of the resources. Add the directory to the classpath:e.g. In the build.sbt file:unmanagedClasspath in Test += baseDirectory.value / "src/test/features"This works for me, the Runner is something that basically hooks into JUnit runner vs the plugin that provides a new command. I may look at trying to combine them, when I originally wrote it, wanted to keep them separate (we had projects where BDD feature files had to be run separately to the test/it tests that we were running on check-in), the runner was added in case someone wanted to hook in the cucumber into 'sbt test'.—

**Comment by lewismj** [comment]
Thanks, if its still a problem, I'll open up the issue again.
