### ISSUE TITLE
Cucumber 1.2.6 / Scala 2.12

### ISSUE THREAD

**Issue by lewismj** [lewismj/cucumber#28]
I noticed this issue, raised on Cucumber github, think it won't affect the plugin, but the runner:

https://github.com/cucumber/cucumber-jvm/issues/1087

**Comment by lewismj** [comment]
I will release a cross build of the test framework once Cucumber 1.2.6 is available.

**Comment by lewismj** [comment]
I think some changes have been merged into the master branch of cucumber, I will test that this evening and do an interim release off the master cucumber branch if this works.

**Comment by lewismj** [comment]
Looks like a commit (cucumber) into master, as soon as its in snapshot I should be able to (finally) build a release.

**Comment by lewismj** [comment]
Just published a new version to sonatype.

**Comment by lewismj** [comment]
Will re-open if required.

**Comment by pallavikaran** [comment]
I have scala 2.12.1 version
What changes do I need to make here:


libraryDependencies ++= Seq(
  "org.scala-lang" % "scala-reflect" % "2.11.8",
  "org.scala-lang.modules" % "scala-xml_2.11" % "1.0.4"
)

libraryDependencies += "info.cukes" % "cucumber-scala_2.11" % "1.2.4"
libraryDependencies += "info.cukes" % "cucumber-junit" % "1.2.4"
libraryDependencies += "junit" % "junit" % "4.12"
libraryDependencies += "org.scala-lang" % "scala-lirary" % "2.11.1"
libraryDependencies += "info.cukes" % "cucumber-picocontainer" % "1.1.8"
libraryDependencies += "org.slf4j" % "slf4j-log4j12" % "1.2"
libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % "test"
libraryDependencies += "org.scalactic" %% "scalactic" % "2.2.6"
libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.6" % "test"

**Comment by fabiocaso** [comment]
I am still getting this issue if I try scala 2.12.x, is this been fixed? 
`Exception in thread "main" java.lang.NoSuchMethodError: cucumber.api.scala.ScalaDsl.$init$(Lcucumber/api/scala/ScalaDsl;)V`

```
version := "1.2.1"
scalaVersion := "2.12.6"

libraryDependencies ++= {

  Seq(
    "com.typesafe"               % "config"                  % "1.3.3" % "test",
    "org.scalactic" %% "scalactic" % "3.0.5",
    "org.scalatest" %% "scalatest" % "3.0.5" % "test",
    "info.cukes"                 %% "cucumber-scala"         % "1.2.5" % "test",
    "info.cukes"                 % "cucumber-junit"          % "1.2.5" % "test",
    "com.novocode"               % "junit-interface"         % "0.11" % "test",
    "org.seleniumhq.selenium" % "selenium-java" % "3.14.0" % "test",
    "com.typesafe.scala-logging" %% "scala-logging" % "3.9.0",
    "ch.qos.logback"             % "logback-classic"         % "1.2.3",
    "commons-pool"               % "commons-pool"            % "1.6",
    "com.iheart"                 %% "ficus"                  % "1.4.0",
    "net.masterthought" % "cucumber-reporting" % "3.20.0",
    "net.lightbody.bmp"          % "browsermob-core"         % "2.1.5" % "test",
    "com.typesafe.play" %% "play-json" % "2.6.9",
    "org.scalaj"                 %% "scalaj-http"            % "2.3.0",
    "com.browserstack" % "browserstack-local-java" % "1.0.2"
  )
}

parallelExecution in Test := true
testForkedParallel in Test := true

resolvers ++= Seq(
  "sonatype-releases" at "https://oss.sonatype.org/content/repositories/releases/",
  "Artima Maven Repository" at "http://repo.artima.com/releases",
  Resolver.jcenterRepo
```

**Comment by lewismj** [comment]
I will take a look at updating the packages this weekend... hopefully, clear up, I've used with Scala 2.12
