### ISSUE TITLE
Not possible to use monochrome output for cucumber-runner

### ISSUE THREAD

**Issue by pjedruszuk** [lewismj/cucumber#30]
Options for cucumber-runner seems to be hardcoded. It does not respect --monochrome argument or CucumberPlugin.monochrome setting.

**Comment by lewismj** [comment]
I'll setup a waffle board and organize a few updates into a release.

**Comment by lewismj** [comment]
For the plugin, I had a 
monochrome:= false
hard-coded setting for some reason. So that fix was easy, I'll look at tidying up the runer a bit and do a new release. Later today hopefully. I may as a temp. measure release the plugin (the sbt cucumber command) update before the runner (separate project that allows  cucumber tests  as part of sbt test).

**Comment by lewismj** [comment]
I had a look, I think this ticket (along with another) will get bundled into a bigger bit of work, cutting over to using:
 "org.scala-sbt" % "test-interface" % "1.0"
from scala-tools.
The plugin iteself is fine as standalong command, but the runner will need a longer term fix, probably something for me to do next weekend.

**Comment by lewismj** [comment]
I've done the first bit of this, which is to re-write the runner to use the sbt test-interface from the (much) older scala tools interface. I need to figure out how to pass the arguments in, I default some, but even though I set some in my build sbt and then look at the framework creation - don't see them. So, needs a bit more investigation.

**Comment by lewismj** [comment]
Found the issue, should be fixed soon. Will be 0.0.8 version of the runner, will be published later today.

**Comment by seanrand57** [comment]
Nice work!

Sent from my iPhone

On Apr 2, 2017, at 1:01 PM, Michael Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


Found the issue, should be fixed soon. Will be 0.0.8 version of the runner, will be published later today.

**Comment by lewismj** [comment]
@seanrand57 thanks!

Maven will take some time to update, but version 0.0.8 of the test runner has just been published (0.0.7 was short lived;)

I've also tidied up the documentation. It makes it clearer (hopefully) that the plugin and runner are completley separate entities. 

i.e. You don't need to use the plugin, if you just want to run Cucumber via 'sbt test'.

The plugin is useful if you want to run 'sbt cucumber' independently of the unit tests.

@pjedruszuk Thanks for the Issue - it forced me to clean up the runner code (its had a re-write, so it should have nicer test output too) and this issue should be fixed.

It usually takes a few hours before the update becomes available everywhere.

**Comment by lewismj** [comment]
n.b. I have updated the documentation.

In particular, use CucumberSpec as the base class for your Cucumber test suite.

There were a few badly named things in the older versions. Hopefully its easy for people to change on upgrade (its just cut/paste).

Anyway, the plus side is that this version should allow pass through of all the Cucumber options. I may 'retire' the plugin as the standalone command is a bit confusing....

**Comment by seanrand57** [comment]
Sbt cucumber has been decom'd at my end and in the business recently. We use SBT test for existing so unless anyone else uses sbt cucumber, if it's too much to upkeep and not worth it, maybe safe to decom?

Cheers Mike!

Sent from my iPhone

On Apr 2, 2017, at 1:59 PM, Michael Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


n.b. I have updated the documentation.

In particular, use CucumberSpec as the base class for your Cucumber test suite.

There were a few badly named things in the older versions. Hopefully its easy for people to change on upgrade (its just cut/paste).

Anyway, the plus side is that this version should allow pass through of all the Cucumber options. I may 'retire' the plugin as the standalone command is a bit confusing....

**Comment by lewismj** [comment]
Yes, thanks, I may well take it out of the documentation. Or at least mark it as deprecated in a couple of weeks time.

**Comment by seanrand57** [comment]
Sounds good! Nice one Mike

Sent from my iPhone

On Apr 2, 2017, at 2:10 PM, Michael Lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, thanks, I may well take it out of the documentation. Or at least mark it as deprecated in a couple of weeks time.

**Comment by pjedruszuk** [comment]
@lewismj Thank you for implementing this so quickly! I'll give it a try today.
