### ISSUE TITLE
[Question] How to run a single feature/example

### ISSUE THREAD

**Issue by tasuki** [lewismj/cucumber#32]
Hi, is it possible to run a single feature/example without the plugin? In the sbt console, I currently use `testOnly *CucumberTestSuite` to only run cucumber tests, but would love to have more control!

**Comment by lewismj** [comment]
I think the plugin you can just do  
sbt "cucumber --tags ~@my-tag"
For the test framework, I've always specified test options as:
testOptions in Test += Tests.Argument(framework,"--plugin","json:/tmp/json")
in my build.sbt, 
I'm not sure if 'testOptions' can be set on the sbt command line. I will take a look, if not, I'll try to come up with a suitable feature.

**Comment by tasuki** [comment]
Michael, thank you for the fast answer!
