### ISSUE TITLE
[Question] Tag_Expression for '--tags'

### ISSUE THREAD

**Issue by chaochana** [lewismj/cucumber#38]
Hi,

Please help me on how to use multiple tags for '--tags' option for cucumber plugin.

I plan to use it in many ways like my cucumber repo consists of test for many modules; a, b, and c

It works as expected when using single tag; `"cucumber --tags @a"` or `"cucumber --tags ~@a"` 
But when I tried `cucumber --tags @a,@ready` or `cucumber --tags @b,@ready` which expect to have test for "@a and @ready" but it's "@a or @ready" instead.

And when I see you mention TAG_EXPRESSION in command help then I check this link  [https://docs.cucumber.io/tag-expressions/](https://docs.cucumber.io/tag-expressions/)
But when I tried to follow, I've got the error

```
> cucumber -d --tags '@foo and @bar'
[error] Exception in thread "main" java.lang.IllegalArgumentException: Not a file or directory: C:\Code\pricing-scala-test\and
```

Thank you very much in advance.

Note:
```
> cucumber -v
[info] 1.2.4
```

```
addSbtPlugin("com.waioeka.sbt" % "cucumber-plugin" % "0.1.6")
```

**Comment by chaochana** [comment]
I figure it out how to use multiple tags for this command line plugin:

@a or @b =>  `cucumber --tag @a,@b`
@a and @b => `cucumber --tags @a --tags @b`
 
Issue Closed. not an issue actually :)

**Comment by lewismj** [comment]
thanks for posting out the explanation.
