### ISSUE TITLE
Request Release Artifact to Sonatype OSS

### ISSUE THREAD

**Issue by andyjcboyle** [lewismj/cucumber#4]
Hi @lewismj 
Your plugin saved me a lot of pain actually .. much appreciated thanks!

Would it be possible to release it to Sonatype OSS ... issue is I have a project which uses SAAS build tool which fails at this point. There are a few hacky ways around but would be better if the dependency was on released, accessible artefact.

So basically the steps here http://central.sonatype.org/pages/ossrh-guide.html
It is a wee bit of pain setup.
If this isn;t something you fancy doing I can either do it linking to this repo ( but I would need write access on the repo ) or I can clone it and do it that way ( I would use a different package structure to not steal yours :-) )

Can you let me know what option you prefer.

Thanks again.
Andy

**Comment by lewismj** [comment]
Hi,
No worries, I have a slight code change (we use it internally) around passing in tag parameters to add. I'm in the middle of a Coursera course for the next few days so I can do it later or if you need it, I'll give you write access to the repo ... you may need to let me know how I do that .. in the meantime, I'll have a dig around git hub and see if I can't get it working...

**Comment by lewismj** [comment]
Hi,
I added you as a collaborator, hopefully that does the trick. I'll merge in the (minor) update this evening (UK time).

**Comment by lewismj** [comment]
Hi,
I've raised a new project request https://issues.sonatype.org/browse/OSSRH-22960 
I will publish as soon as I can, once the JIRA is done..

**Comment by andyjcboyle** [comment]
Hey Michael

okay dokes, nice. There is no rush on my part whatsoever. Personal project in own time etc and it is in no way a blocker as everything obviously locally works fine.

If you want me to do anything then let me know.

Cheers,
Andy

**Comment by lewismj** [comment]
Hi, the repo has been created. I've checked in some changes (organization to com.waioeka from com.waioeka.sbt to be in line with Sonatype recommendations). There is some additional work, re: signing files etc.. that I need to look into but will try to get it published over the weekend or early next week at the latest.

**Comment by andyjcboyle** [comment]
Hey - thanks so much, that's great. 
Hope you enjoyed the Coursera course.

**Comment by lewismj** [comment]
Didn't get chance over w/e, hopefully tonight/tomorrow at the latest, I'll sort out publishing to Sonatype.

**Comment by andyjcboyle** [comment]
Hey. NPS at all.

**Comment by lewismj** [comment]
Hi,
Have you used the sbt pgp signing plugin? I've got the plugin, but the documentation doesn't seem to state how to actually run the plugin itself ... this may take a bit of time ;)

**Comment by lewismj** [comment]
Getting a bit further now, I've published to staging, need to tidy up some of the build.sbt to include homepage and other stuff and publish a release. Hopefully done soon, sorry for the wait.

**Comment by andyjcboyle** [comment]
:-) sounds like fun .... sorry! Not used it for a few years. I can give it a go this evening though

**Comment by lewismj** [comment]
I'm going to wait a few hours, the jars seemed to publish to staging fine, when I closed and released, I could only see the 'runner' not the sbt plugin (I published both). I separately published the sbt plugin. But can only see the runner when I search for it in the release repos, I'll wait a while and see if it gets published, if not, I'll comment on the JIRA that I raised. Hopefully sorted soon.

**Comment by lewismj** [comment]
Hi, I think artifacts are published now:
http://search.maven.org/#search%7Cga%7C1%7Cwaioeka
If you wouldn't mind double checking.  I can add some of the updates (tag handling etc...)

**Comment by andyjcboyle** [comment]
Yes I can see okay ... nice one!
I am prevented from having github fun during daytime but tonight I will make the dependency changes in project and test works in SAAS CI land too.

**Comment by lewismj** [comment]
Thanks for testing.

**Comment by andyjcboyle** [comment]
Gold star and a chocolate biscuit sir! Green build in Codeship now ... thank you so much!

**Comment by lewismj** [comment]
Thanks for letting me know, glad its useful.  I hope to add some support for tags and a few other features that we use where I work..

**Comment by lewismj** [comment]
I added a minor change, so now you can pass through Cucumber arguments, this is useful as you can pass through the --tags parameter to skip/include tests. There is a comment added to the ReadMe.

**Comment by lewismj** [comment]
I don't suppose you know what I would need to add to my .travis.yaml file? I just like to get it to build all the different projects at the moment ...

**Comment by andyjcboyle** [comment]
Not really used Travis before but I'd happily take a look and try. So basically you currently build this locally and are looking to push it to travis and need to work out the incantation to build each project without restructuring as it is - that about the size of it?

**Comment by lewismj** [comment]
I think I've almost figured it out, I'll try to add in some top level Scala project that builds the others, I think the travis.yaml but is surprisingly simple. In the next few days, I'll hopefully have CI integration.
